// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// R.cpp
bool cpp_all_finite(cpp11::doubles x);
extern "C" SEXP _logmu_cpp_all_finite(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_all_finite(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x)));
  END_CPP11
}
// R.cpp
cpp11::doubles cpp_matrix_q_to_log_mu(cpp11::doubles q_matrix);
extern "C" SEXP _logmu_cpp_matrix_q_to_log_mu(SEXP q_matrix) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_matrix_q_to_log_mu(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(q_matrix)));
  END_CPP11
}
// R.cpp
cpp11::doubles cpp_slow_lookup_log_mu(cpp11::doubles log_mu_matrix, int x0_clicks, int t0_clicks, int b_clicks, cpp11::integers t_clicks);
extern "C" SEXP _logmu_cpp_slow_lookup_log_mu(SEXP log_mu_matrix, SEXP x0_clicks, SEXP t0_clicks, SEXP b_clicks, SEXP t_clicks) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_slow_lookup_log_mu(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(log_mu_matrix), cpp11::as_cpp<cpp11::decay_t<int>>(x0_clicks), cpp11::as_cpp<cpp11::decay_t<int>>(t0_clicks), cpp11::as_cpp<cpp11::decay_t<int>>(b_clicks), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(t_clicks)));
  END_CPP11
}
// aev.cpp
cpp11::doubles cpp_deviance_residual(cpp11::doubles A, cpp11::doubles E, cpp11::doubles V);
extern "C" SEXP _logmu_cpp_deviance_residual(SEXP A, SEXP E, SEXP V) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_deviance_residual(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(A), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(E), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(V)));
  END_CPP11
}
// aev.cpp
void cpp_validate_aev(cpp11::doubles A, cpp11::doubles E, cpp11::doubles V);
extern "C" SEXP _logmu_cpp_validate_aev(SEXP A, SEXP E, SEXP V) {
  BEGIN_CPP11
    cpp_validate_aev(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(A), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(E), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(V));
    return R_NilValue;
  END_CPP11
}
// vec_ops_for_R.cpp
cpp11::strings cpp_vec_active_tier();
extern "C" SEXP _logmu_cpp_vec_active_tier() {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_vec_active_tier());
  END_CPP11
}
// vec_ops_for_R.cpp
int cpp_vec_active_lanes();
extern "C" SEXP _logmu_cpp_vec_active_lanes() {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_vec_active_lanes());
  END_CPP11
}
// vec_ops_for_R.cpp
bool cpp_build_optimised();
extern "C" SEXP _logmu_cpp_build_optimised() {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_build_optimised());
  END_CPP11
}
// vec_ops_for_R.cpp
bool cpp_build_asserts_disabled();
extern "C" SEXP _logmu_cpp_build_asserts_disabled() {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_build_asserts_disabled());
  END_CPP11
}
// vec_ops_for_R.cpp
cpp11::doubles cpp_vec_neg(cpp11::doubles x);
extern "C" SEXP _logmu_cpp_vec_neg(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_vec_neg(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x)));
  END_CPP11
}
// vec_ops_for_R.cpp
cpp11::doubles cpp_vec_exp(cpp11::doubles x);
extern "C" SEXP _logmu_cpp_vec_exp(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_vec_exp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x)));
  END_CPP11
}
// vec_ops_for_R.cpp
cpp11::doubles cpp_vec_expm1(cpp11::doubles x);
extern "C" SEXP _logmu_cpp_vec_expm1(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_vec_expm1(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x)));
  END_CPP11
}
// vec_ops_for_R.cpp
cpp11::doubles cpp_vec_log(cpp11::doubles x);
extern "C" SEXP _logmu_cpp_vec_log(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_vec_log(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x)));
  END_CPP11
}
// vec_ops_for_R.cpp
cpp11::doubles cpp_vec_log1p(cpp11::doubles x);
extern "C" SEXP _logmu_cpp_vec_log1p(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_vec_log1p(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x)));
  END_CPP11
}
// vec_ops_for_R.cpp
cpp11::doubles cpp_vec_m_from_q(cpp11::doubles x);
extern "C" SEXP _logmu_cpp_vec_m_from_q(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_vec_m_from_q(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x)));
  END_CPP11
}
// vec_ops_for_R.cpp
cpp11::doubles cpp_vec_add(cpp11::doubles x, cpp11::doubles y);
extern "C" SEXP _logmu_cpp_vec_add(SEXP x, SEXP y) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_vec_add(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y)));
  END_CPP11
}
// vec_ops_for_R.cpp
cpp11::doubles cpp_vec_sub(cpp11::doubles x, cpp11::doubles y);
extern "C" SEXP _logmu_cpp_vec_sub(SEXP x, SEXP y) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_vec_sub(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y)));
  END_CPP11
}
// vec_ops_for_R.cpp
cpp11::doubles cpp_vec_mul(cpp11::doubles x, cpp11::doubles y);
extern "C" SEXP _logmu_cpp_vec_mul(SEXP x, SEXP y) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_vec_mul(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y)));
  END_CPP11
}
// vec_ops_for_R.cpp
cpp11::doubles cpp_vec_div(cpp11::doubles x, cpp11::doubles y);
extern "C" SEXP _logmu_cpp_vec_div(SEXP x, SEXP y) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_vec_div(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y)));
  END_CPP11
}
// vec_ops_for_R.cpp
cpp11::doubles cpp_vec_pow(cpp11::doubles x, cpp11::doubles y);
extern "C" SEXP _logmu_cpp_vec_pow(SEXP x, SEXP y) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_vec_pow(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y)));
  END_CPP11
}
// vec_ops_for_R.cpp
cpp11::doubles cpp_vec_max(cpp11::doubles x, cpp11::doubles y);
extern "C" SEXP _logmu_cpp_vec_max(SEXP x, SEXP y) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_vec_max(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y)));
  END_CPP11
}
// vec_ops_for_R.cpp
cpp11::doubles cpp_vec_min(cpp11::doubles x, cpp11::doubles y);
extern "C" SEXP _logmu_cpp_vec_min(SEXP x, SEXP y) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_vec_min(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y)));
  END_CPP11
}
// vec_ops_for_R.cpp
cpp11::doubles cpp_vec_clamp(cpp11::doubles x, double min, double max);
extern "C" SEXP _logmu_cpp_vec_clamp(SEXP x, SEXP min, SEXP max) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_vec_clamp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<double>>(min), cpp11::as_cpp<cpp11::decay_t<double>>(max)));
  END_CPP11
}
// veil_for_R.cpp
cpp11::list cpp_veil_ingest_ast(cpp11::list node, cpp11::strings column_names);
extern "C" SEXP _logmu_cpp_veil_ingest_ast(SEXP node, SEXP column_names) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_veil_ingest_ast(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(node), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(column_names)));
  END_CPP11
}
// veil_for_R.cpp
cpp11::list cpp_veil_prepare(cpp11::list node, cpp11::list columns);
extern "C" SEXP _logmu_cpp_veil_prepare(SEXP node, SEXP columns) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_veil_prepare(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(node), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(columns)));
  END_CPP11
}
// veil_for_R.cpp
cpp11::list cpp_veil_scan(cpp11::list columns);
extern "C" SEXP _logmu_cpp_veil_scan(SEXP columns) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_veil_scan(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(columns)));
  END_CPP11
}
// veil_for_R.cpp
cpp11::list cpp_veil_record_chunks(int records);
extern "C" SEXP _logmu_cpp_veil_record_chunks(SEXP records) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_veil_record_chunks(cpp11::as_cpp<cpp11::decay_t<int>>(records)));
  END_CPP11
}
// veil_for_R.cpp
int cpp_veil_default_threads();
extern "C" SEXP _logmu_cpp_veil_default_threads() {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_veil_default_threads());
  END_CPP11
}
// veil_for_R.cpp
cpp11::integers cpp_veil_time_scales();
extern "C" SEXP _logmu_cpp_veil_time_scales() {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_veil_time_scales());
  END_CPP11
}
// veil_for_R.cpp
cpp11::doubles cpp_veil_to_years(cpp11::integers clicks);
extern "C" SEXP _logmu_cpp_veil_to_years(SEXP clicks) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_veil_to_years(cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(clicks)));
  END_CPP11
}
// veil_for_R.cpp
cpp11::integers cpp_veil_to_clicks(cpp11::doubles years);
extern "C" SEXP _logmu_cpp_veil_to_clicks(SEXP years) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_veil_to_clicks(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(years)));
  END_CPP11
}
// veil_for_R.cpp
cpp11::list cpp_veil_fold(cpp11::list node, cpp11::list columns);
extern "C" SEXP _logmu_cpp_veil_fold(SEXP node, SEXP columns) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_veil_fold(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(node), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(columns)));
  END_CPP11
}
// veil_for_R.cpp
cpp11::list cpp_veil_eval_multi(cpp11::list nodes, cpp11::list columns);
extern "C" SEXP _logmu_cpp_veil_eval_multi(SEXP nodes, SEXP columns) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_veil_eval_multi(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(nodes), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(columns)));
  END_CPP11
}
// veil_for_R.cpp
cpp11::list cpp_veil_eval(cpp11::list node, cpp11::list columns);
extern "C" SEXP _logmu_cpp_veil_eval(SEXP node, SEXP columns) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_veil_eval(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(node), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(columns)));
  END_CPP11
}
// veil_for_R.cpp
cpp11::list cpp_veil_integrate(cpp11::list node, cpp11::list columns, int time_scale, SEXP include);
extern "C" SEXP _logmu_cpp_veil_integrate(SEXP node, SEXP columns, SEXP time_scale, SEXP include) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_veil_integrate(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(node), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(columns), cpp11::as_cpp<cpp11::decay_t<int>>(time_scale), cpp11::as_cpp<cpp11::decay_t<SEXP>>(include)));
  END_CPP11
}
// veil_for_R.cpp
cpp11::list cpp_veil_aev(cpp11::list mortality, SEXP weight, cpp11::list columns, int time_scale, SEXP include, double overdispersion, int threads);
extern "C" SEXP _logmu_cpp_veil_aev(SEXP mortality, SEXP weight, SEXP columns, SEXP time_scale, SEXP include, SEXP overdispersion, SEXP threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_veil_aev(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(mortality), cpp11::as_cpp<cpp11::decay_t<SEXP>>(weight), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(columns), cpp11::as_cpp<cpp11::decay_t<int>>(time_scale), cpp11::as_cpp<cpp11::decay_t<SEXP>>(include), cpp11::as_cpp<cpp11::decay_t<double>>(overdispersion), cpp11::as_cpp<cpp11::decay_t<int>>(threads)));
  END_CPP11
}
// veil_for_R.cpp
cpp11::list cpp_veil_run(cpp11::list specs, cpp11::list columns, int time_scale, bool keep_contributions, int threads);
extern "C" SEXP _logmu_cpp_veil_run(SEXP specs, SEXP columns, SEXP time_scale, SEXP keep_contributions, SEXP threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_veil_run(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(specs), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(columns), cpp11::as_cpp<cpp11::decay_t<int>>(time_scale), cpp11::as_cpp<cpp11::decay_t<bool>>(keep_contributions), cpp11::as_cpp<cpp11::decay_t<int>>(threads)));
  END_CPP11
}
// veil_for_R.cpp
cpp11::list cpp_veil_intervals(cpp11::list node, cpp11::list columns);
extern "C" SEXP _logmu_cpp_veil_intervals(SEXP node, SEXP columns) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_veil_intervals(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(node), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(columns)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_logmu_cpp_all_finite",             (DL_FUNC) &_logmu_cpp_all_finite,             1},
    {"_logmu_cpp_build_asserts_disabled", (DL_FUNC) &_logmu_cpp_build_asserts_disabled, 0},
    {"_logmu_cpp_build_optimised",        (DL_FUNC) &_logmu_cpp_build_optimised,        0},
    {"_logmu_cpp_deviance_residual",      (DL_FUNC) &_logmu_cpp_deviance_residual,      3},
    {"_logmu_cpp_matrix_q_to_log_mu",     (DL_FUNC) &_logmu_cpp_matrix_q_to_log_mu,     1},
    {"_logmu_cpp_slow_lookup_log_mu",     (DL_FUNC) &_logmu_cpp_slow_lookup_log_mu,     5},
    {"_logmu_cpp_validate_aev",           (DL_FUNC) &_logmu_cpp_validate_aev,           3},
    {"_logmu_cpp_vec_active_lanes",       (DL_FUNC) &_logmu_cpp_vec_active_lanes,       0},
    {"_logmu_cpp_vec_active_tier",        (DL_FUNC) &_logmu_cpp_vec_active_tier,        0},
    {"_logmu_cpp_vec_add",                (DL_FUNC) &_logmu_cpp_vec_add,                2},
    {"_logmu_cpp_vec_clamp",              (DL_FUNC) &_logmu_cpp_vec_clamp,              3},
    {"_logmu_cpp_vec_div",                (DL_FUNC) &_logmu_cpp_vec_div,                2},
    {"_logmu_cpp_vec_exp",                (DL_FUNC) &_logmu_cpp_vec_exp,                1},
    {"_logmu_cpp_vec_expm1",              (DL_FUNC) &_logmu_cpp_vec_expm1,              1},
    {"_logmu_cpp_vec_log",                (DL_FUNC) &_logmu_cpp_vec_log,                1},
    {"_logmu_cpp_vec_log1p",              (DL_FUNC) &_logmu_cpp_vec_log1p,              1},
    {"_logmu_cpp_vec_m_from_q",           (DL_FUNC) &_logmu_cpp_vec_m_from_q,           1},
    {"_logmu_cpp_vec_max",                (DL_FUNC) &_logmu_cpp_vec_max,                2},
    {"_logmu_cpp_vec_min",                (DL_FUNC) &_logmu_cpp_vec_min,                2},
    {"_logmu_cpp_vec_mul",                (DL_FUNC) &_logmu_cpp_vec_mul,                2},
    {"_logmu_cpp_vec_neg",                (DL_FUNC) &_logmu_cpp_vec_neg,                1},
    {"_logmu_cpp_vec_pow",                (DL_FUNC) &_logmu_cpp_vec_pow,                2},
    {"_logmu_cpp_vec_sub",                (DL_FUNC) &_logmu_cpp_vec_sub,                2},
    {"_logmu_cpp_veil_aev",               (DL_FUNC) &_logmu_cpp_veil_aev,               7},
    {"_logmu_cpp_veil_default_threads",   (DL_FUNC) &_logmu_cpp_veil_default_threads,   0},
    {"_logmu_cpp_veil_eval",              (DL_FUNC) &_logmu_cpp_veil_eval,              2},
    {"_logmu_cpp_veil_eval_multi",        (DL_FUNC) &_logmu_cpp_veil_eval_multi,        2},
    {"_logmu_cpp_veil_fold",              (DL_FUNC) &_logmu_cpp_veil_fold,              2},
    {"_logmu_cpp_veil_ingest_ast",        (DL_FUNC) &_logmu_cpp_veil_ingest_ast,        2},
    {"_logmu_cpp_veil_integrate",         (DL_FUNC) &_logmu_cpp_veil_integrate,         4},
    {"_logmu_cpp_veil_intervals",         (DL_FUNC) &_logmu_cpp_veil_intervals,         2},
    {"_logmu_cpp_veil_prepare",           (DL_FUNC) &_logmu_cpp_veil_prepare,           2},
    {"_logmu_cpp_veil_record_chunks",     (DL_FUNC) &_logmu_cpp_veil_record_chunks,     1},
    {"_logmu_cpp_veil_run",               (DL_FUNC) &_logmu_cpp_veil_run,               5},
    {"_logmu_cpp_veil_scan",              (DL_FUNC) &_logmu_cpp_veil_scan,              1},
    {"_logmu_cpp_veil_time_scales",       (DL_FUNC) &_logmu_cpp_veil_time_scales,       0},
    {"_logmu_cpp_veil_to_clicks",         (DL_FUNC) &_logmu_cpp_veil_to_clicks,         1},
    {"_logmu_cpp_veil_to_years",          (DL_FUNC) &_logmu_cpp_veil_to_years,          1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_logmu(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
