# Generated by cpp11: do not edit by hand

cpp_all_finite <- function(x) {
  .Call(`_logmu_cpp_all_finite`, x)
}

cpp_matrix_q_to_log_mu <- function(q_matrix) {
  .Call(`_logmu_cpp_matrix_q_to_log_mu`, q_matrix)
}

cpp_slow_lookup_log_mu <- function(log_mu_matrix, x0_clicks, t0_clicks, b_clicks, t_clicks) {
  .Call(`_logmu_cpp_slow_lookup_log_mu`, log_mu_matrix, x0_clicks, t0_clicks, b_clicks, t_clicks)
}

cpp_deviance_residual <- function(A, E, V) {
  .Call(`_logmu_cpp_deviance_residual`, A, E, V)
}

cpp_validate_aev <- function(A, E, V) {
  invisible(.Call(`_logmu_cpp_validate_aev`, A, E, V))
}

cpp_vec_active_tier <- function() {
  .Call(`_logmu_cpp_vec_active_tier`)
}

cpp_vec_active_lanes <- function() {
  .Call(`_logmu_cpp_vec_active_lanes`)
}

cpp_vec_neg <- function(x) {
  .Call(`_logmu_cpp_vec_neg`, x)
}

cpp_vec_exp <- function(x) {
  .Call(`_logmu_cpp_vec_exp`, x)
}

cpp_vec_expm1 <- function(x) {
  .Call(`_logmu_cpp_vec_expm1`, x)
}

cpp_vec_log <- function(x) {
  .Call(`_logmu_cpp_vec_log`, x)
}

cpp_vec_log1p <- function(x) {
  .Call(`_logmu_cpp_vec_log1p`, x)
}

cpp_vec_m_from_q <- function(x) {
  .Call(`_logmu_cpp_vec_m_from_q`, x)
}

cpp_vec_add <- function(x, y) {
  .Call(`_logmu_cpp_vec_add`, x, y)
}

cpp_vec_sub <- function(x, y) {
  .Call(`_logmu_cpp_vec_sub`, x, y)
}

cpp_vec_mul <- function(x, y) {
  .Call(`_logmu_cpp_vec_mul`, x, y)
}

cpp_vec_div <- function(x, y) {
  .Call(`_logmu_cpp_vec_div`, x, y)
}

cpp_vec_pow <- function(x, y) {
  .Call(`_logmu_cpp_vec_pow`, x, y)
}

cpp_vec_max <- function(x, y) {
  .Call(`_logmu_cpp_vec_max`, x, y)
}

cpp_vec_min <- function(x, y) {
  .Call(`_logmu_cpp_vec_min`, x, y)
}

cpp_vec_clamp <- function(x, min, max) {
  .Call(`_logmu_cpp_vec_clamp`, x, min, max)
}

cpp_veil_ingest_ast <- function(node, column_names) {
  .Call(`_logmu_cpp_veil_ingest_ast`, node, column_names)
}

cpp_veil_prepare <- function(node, columns) {
  .Call(`_logmu_cpp_veil_prepare`, node, columns)
}

cpp_veil_scan <- function(columns) {
  .Call(`_logmu_cpp_veil_scan`, columns)
}

cpp_veil_record_chunks <- function(records) {
  .Call(`_logmu_cpp_veil_record_chunks`, records)
}

cpp_veil_default_threads <- function() {
  .Call(`_logmu_cpp_veil_default_threads`)
}

cpp_veil_time_scales <- function() {
  .Call(`_logmu_cpp_veil_time_scales`)
}

cpp_veil_to_years <- function(clicks) {
  .Call(`_logmu_cpp_veil_to_years`, clicks)
}

cpp_veil_to_clicks <- function(years) {
  .Call(`_logmu_cpp_veil_to_clicks`, years)
}

cpp_veil_fold <- function(node, columns) {
  .Call(`_logmu_cpp_veil_fold`, node, columns)
}

cpp_veil_eval_multi <- function(nodes, columns) {
  .Call(`_logmu_cpp_veil_eval_multi`, nodes, columns)
}

cpp_veil_eval <- function(node, columns) {
  .Call(`_logmu_cpp_veil_eval`, node, columns)
}

cpp_veil_integrate <- function(node, columns, time_scale, include) {
  .Call(`_logmu_cpp_veil_integrate`, node, columns, time_scale, include)
}

cpp_veil_aev <- function(mortality, weight, columns, time_scale, include, overdispersion, threads) {
  .Call(`_logmu_cpp_veil_aev`, mortality, weight, columns, time_scale, include, overdispersion, threads)
}

cpp_veil_run <- function(specs, columns, time_scale, keep_contributions, threads) {
  .Call(`_logmu_cpp_veil_run`, specs, columns, time_scale, keep_contributions, threads)
}

cpp_veil_intervals <- function(node, columns) {
  .Call(`_logmu_cpp_veil_intervals`, node, columns)
}
